#!/usr/bin/env python3
"""Generate review-5 validation tables from results/review5/*.json."""
from __future__ import annotations

import collections
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
R5 = ROOT / "results" / "review5"
TABLES = ROOT.parent / "actionshap-overleaf" / "tables"
BS = "\\\\"


def main() -> None:
    L: list[str] = []
    L.append("% Review-5 validation tables (generated by scripts/make_review5_tables.py).")

    # --- SASRec quality -------------------------------------------------
    L.append(r"\begin{table}[!htbp]\centering\scriptsize\setlength{\tabcolsep}{3pt}")
    L.append(
        "\\caption{SASRec recommendation quality, five seeds; full-catalogue ranking\n"
        "against all unseen items on 1,000 users. Cohort rows use the replication\n"
        "training recipe (cohort-only histories, ten leave-one-out epochs); full-corpus\n"
        "rows train on every eligible user for thirty epochs with the chronological\n"
        "next-item objective. Neither configuration beats popularity, so the SASRec\n"
        "results in Table~\\ref{tab:review3} demonstrate attribution transfer under a\n"
        "sequential scorer, not competitive recommendation; the quality gate's purpose\n"
        "is precisely to flag this, and the tuning gap is reported as a limitation.}"
    )
    L.append(r"\label{tab:review5-sasrec-quality}")
    L.append(r"\begin{tabular}{@{}lrrrrrr@{}}")
    L.append(r"\toprule")
    L.append("Run & NDCG@10 & HR@10 & MRR & Pop.\\ NDCG@10 & Masking $\\Delta$ & Gate " + BS)
    L.append(r"\midrule")
    runs = [("Amazon", "sasrec_quality_amazon.json", "cohort, 10 ep"),
            ("Amazon", "sasrec_quality_trainall_amazon.json", "full corpus, 30 ep"),
            ("ML-1M", "sasrec_quality_movielens.json", "cohort, 10 ep"),
            ("ML-1M", "sasrec_quality_trainall_movielens.json", "full corpus, 30 ep")]
    for ds, f, cfg in runs:
        path = R5 / f
        if not path.exists():
            continue
        d = json.load(open(path))
        nd = float(np.mean([r["ndcg10"] for r in d["results"]]))
        hr = float(np.mean([r["hr10"] for r in d["results"]]))
        mrr = float(np.mean([r["mrr"] for r in d["results"]]))
        pop = float(np.mean([r["ndcg10_popularity"] for r in d["results"]]))
        md = float(np.mean([r["mean_abs_masking_delta"] for r in d["results"]]))
        gates = [r["masking_gate_pass"] for r in d["results"]]
        gp = f"{sum(gates)}/5"
        L.append(f"{ds} ({cfg}) & {nd:.4f} & {hr:.4f} & {mrr:.4f} & {pop:.4f} & {md:.4f} & "
                 f"{gp} {BS}")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")

    # --- exact-Shapley distribution -------------------------------------
    L.append(r"\begin{table}[!htbp]\centering\scriptsize\setlength{\tabcolsep}{3pt}")
    L.append(
        "\\caption{Exact-Shapley validation of the reverse-paired estimator on\n"
        "enumerable users ($n_u\\le12$): per-user maximum absolute error quantiles,\n"
        "top-2 signed-action Jaccard between exact- and MC-selected actions, and\n"
        "player-level sign-error rate.}"
    )
    L.append(r"\label{tab:review5-exact-dist}")
    L.append(r"\begin{tabular}{@{}lrrrrrr@{}}")
    L.append(r"\toprule")
    L.append("Dataset & $n$ & err p50 & err p95 & Jaccard mean & Jaccard p5 & sign err. " + BS)
    L.append(r"\midrule")
    for ds, f in [("Amazon", "exact_shapley_distribution_amazon.json"),
                  ("ML-1M", "exact_shapley_distribution_movielens.json")]:
        d = json.load(open(R5 / f))
        a = d["aggregate"]
        j = sorted(r["top2_jaccard"] for r in d["records"])
        L.append(f"{ds} & {d['n_users']} & {a['max_abs_error']['p50']:.2e} & "
                 f"{a['max_abs_error']['p95']:.2e} & {a['top2_jaccard']['mean']:.3f} & "
                 f"{np.percentile(j, 5):.2f} & {a['sign_error']['mean']:.3f} {BS}")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")

    # --- LIME mask design -----------------------------------------------
    order = [("bernoulli", 1.0), ("unique", 1.0), ("enumerate", 1.0),
             ("bernoulli", 0.1), ("bernoulli", 10.0)]
    lbl = {("bernoulli", 1.0): "Bernoulli (primary)", ("unique", 1.0): "Unique masks",
           ("enumerate", 1.0): "Enumerate ($n_u\le9$)", ("bernoulli", 0.1): "Bernoulli",
           ("bernoulli", 10.0): "Bernoulli"}
    L.append(r"\begin{table}[!htbp]\centering\scriptsize\setlength{\tabcolsep}{3pt}")
    L.append(
        "\\caption{LIME mask-design ablation (ItemKNN, 200 users, target margin):\n"
        "the seeded Bernoulli design with replacement, distinct masks without\n"
        "replacement, and full enumeration where feasible, plus the ridge penalty\n"
        "sweep under the Bernoulli design. Users whose attribution or effect vector\n"
        "is constant are excluded (valid/$n$).}"
    )
    L.append(r"\label{tab:review5-lime-masks}")
    L.append(r"\begin{tabular}{@{}lllrrr@{}}")
    L.append(r"\toprule")
    L.append(r"Dataset & Design & Ridge $\alpha$ & valid/$n$ users & Bounded AIA & SD " + BS)
    L.append(r"\midrule")
    for ds, f in [("ML-1M", "lime_mask_ablation_movielens.json"),
                  ("Amazon", "lime_mask_ablation_amazon.json")]:
        path = R5 / f
        if not path.exists():
            continue
        d = json.load(open(path))
        agg = collections.defaultdict(list)
        for r in d["records"]:
            agg[(r["design"], r["ridge_alpha"])].append(r["bounded_aia"])
        for k in order:
            tot = agg.get(k, [])
            if not tot:
                continue
            vals = np.array([x for x in tot if x is not None], dtype=float)
            if len(vals) == 0:
                continue
            L.append(f"{ds} & {lbl[k]} & {k[1]:g} & {len(vals)}/{len(tot)} & "
                     f"{vals.mean():.3f} & {vals.std(ddof=1):.3f} {BS}")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")

    # --- variance components --------------------------------------------
    L.append(r"\begin{table}[!htbp]\centering\scriptsize\setlength{\tabcolsep}{3pt}")
    L.append(
        "\\caption{Profile-model variance components (bounded AIA, 100 users,\n"
        "$M_{\\mathrm{pair}}=100$): fixed model across five attribution seeds versus\n"
        "five model-initialization seeds with fixed attribution.}"
    )
    L.append(r"\label{tab:review5-variance}")
    L.append(r"\begin{tabular}{@{}lrrr@{}}")
    L.append(r"\toprule")
    L.append("Dataset & Attribution-seed var. & Model-seed var. & Cell mean " + BS)
    L.append(r"\midrule")
    for ds, f in [("Amazon", "variance_components_amazon.json"),
                  ("ML-1M", "variance_components_movielens.json")]:
        d = json.load(open(R5 / f))
        L.append(f"{ds} & {d['fixed_model_x_attr_seeds']['mean_of_user_variances']:.4f} & "
                 f"{d['model_seeds_x_fixed_attr']['mean_of_user_variances']:.4f} & "
                 f"{d['fixed_model_x_attr_seeds']['cell_mean']:.3f} {BS}")
    L.append(r"\bottomrule")
    L.append(r"\end{tabular}")
    L.append(r"\end{table}")

    out = TABLES / "review5_validation.tex"
    out.write_text("\n".join(L) + "\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
